// Aixlarity — Merge Gate
//
// Validates and applies patch proposals from parallel sub-agents.
// Enforces scope restrictions, detects file conflicts between agents,
// and applies patches sequentially to the main workspace.
//
// Design: Implements the "parallel intent generation, serialized mutation"
// principle — agents produce patches in isolated worktrees, and the merge
// gate is the single point where state mutations are committed to the
// canonical workspace. Inspired by Kimi Agent Swarm's architecture and
// the git merge queue pattern.

use std::collections::{HashMap, HashSet};
use std::path::Path;
use std::process::Command;

use serde::Serialize;

use crate::tools::path_matches_any_glob;

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

/// A patch proposal generated by a sub-agent in an isolated worktree.
/// This is the structured output that replaces direct filesystem writes.
#[derive(Clone, Debug, Serialize)]
pub struct PatchProposal {
    /// Task name from the coordinator spec.
    pub task_name: String,
    /// Agent identifier.
    pub agent_id: String,
    /// Base commit the worktree was created from.
    pub base_commit: String,
    /// Unified diff of all changes.
    pub unified_diff: String,
    /// Files changed (relative to workspace root).
    pub changed_files: Vec<String>,
    /// Agent's summary of what it did.
    pub summary: String,
    /// Risk assessment from the agent.
    pub risk_notes: String,
}

/// Result of attempting to merge a single patch.
#[derive(Clone, Debug, Serialize)]
#[serde(tag = "result")]
pub enum MergeResult {
    Applied,
    ScopeViolation {
        task_name: String,
        forbidden_files: Vec<String>,
        out_of_scope_files: Vec<String>,
    },
    ApplyFailed {
        task_name: String,
        error: String,
    },
}

/// A detected conflict between two agents' patches.
#[derive(Clone, Debug, Serialize)]
pub struct FileConflict {
    pub file: String,
    pub agents: Vec<String>,
}

/// Full report from the merge gate.
#[derive(Clone, Debug, Serialize)]
pub struct MergeReport {
    pub applied: Vec<String>,
    pub scope_violations: Vec<MergeResult>,
    pub apply_failures: Vec<MergeResult>,
    pub conflicts: Vec<FileConflict>,
}

// ---------------------------------------------------------------------------
// Scope validation
// ---------------------------------------------------------------------------

/// Validate that a patch only touches files within the allowed scope.
/// Returns a list of files that violate the scope.
///
/// Design: This is Layer 1 of the three-layer conflict control —
/// preventing scope violations before any merge attempt.
pub fn validate_scope(
    proposal: &PatchProposal,
    allowed_paths: &[String],
    forbidden_paths: &[String],
) -> MergeResult {
    let mut forbidden_files = Vec::new();
    let mut out_of_scope_files = Vec::new();

    for file in &proposal.changed_files {
        if !forbidden_paths.is_empty() && path_matches_any_glob(file, forbidden_paths) {
            forbidden_files.push(file.clone());
        }
        if !allowed_paths.is_empty() && !path_matches_any_glob(file, allowed_paths) {
            out_of_scope_files.push(file.clone());
        }
    }

    if forbidden_files.is_empty() && out_of_scope_files.is_empty() {
        MergeResult::Applied
    } else {
        MergeResult::ScopeViolation {
            task_name: proposal.task_name.clone(),
            forbidden_files,
            out_of_scope_files,
        }
    }
}

// ---------------------------------------------------------------------------
// Conflict detection
// ---------------------------------------------------------------------------

/// Detect file-level conflicts between proposals in the same batch.
/// If two agents both modified the same file, that's a conflict.
///
/// Design: This is a conservative approach — even if the changes are
/// to different regions of the same file, we flag it. A smarter
/// AST/symbol-level resolver could be added in a future phase.
pub fn detect_file_conflicts(proposals: &[PatchProposal]) -> Vec<FileConflict> {
    let mut file_to_agents: HashMap<String, Vec<String>> = HashMap::new();

    for proposal in proposals {
        for file in &proposal.changed_files {
            file_to_agents
                .entry(file.clone())
                .or_default()
                .push(proposal.task_name.clone());
        }
    }

    file_to_agents
        .into_iter()
        .filter(|(_, agents)| agents.len() > 1)
        .map(|(file, agents)| FileConflict { file, agents })
        .collect()
}

// ---------------------------------------------------------------------------
// Patch application
// ---------------------------------------------------------------------------

/// Apply a unified diff to the workspace using `git apply`.
/// This is the serialized mutation point — only one patch is applied at a time.
///
/// Design: Using `git apply` instead of direct file writes because:
/// 1. It respects line-level context matching (detects stale patches).
/// 2. It's atomic — either the whole patch applies or nothing changes.
/// 3. It produces clear error messages for conflict diagnosis.
pub fn apply_patch_to_workspace(workspace_root: &Path, unified_diff: &str) -> Result<(), String> {
    if unified_diff.trim().is_empty() {
        return Ok(()); // No changes to apply
    }

    let mut apply_child = Command::new("git")
        .args(["apply", "--verbose", "-"])
        .current_dir(workspace_root)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|err| format!("Failed to spawn git apply: {}", err))?;

    if let Some(ref mut stdin) = apply_child.stdin {
        use std::io::Write;
        let _ = stdin.write_all(unified_diff.as_bytes());
    }

    let output = apply_child
        .wait_with_output()
        .map_err(|err| format!("Failed to wait for git apply: {}", err))?;

    if output.status.success() {
        Ok(())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        Err(format!("git apply failed: {}", stderr.trim()))
    }
}

/// Apply all patches from the proposals, with scope validation and conflict detection.
/// Patches are applied sequentially in the order they appear.
///
/// Design: This is the merge gate's main entry point. It implements
/// optimistic concurrency control — patches are validated against the
/// current workspace state, and conflicts are detected file-by-file.
pub fn merge_all(
    workspace_root: &Path,
    proposals: &[PatchProposal],
    task_scopes: &HashMap<String, (Vec<String>, Vec<String>)>, // task_name -> (allowed, forbidden)
) -> MergeReport {
    let mut report = MergeReport {
        applied: Vec::new(),
        scope_violations: Vec::new(),
        apply_failures: Vec::new(),
        conflicts: detect_file_conflicts(proposals),
    };

    // Track which files have already been modified in this merge session
    let mut touched_files: HashSet<String> = HashSet::new();

    for proposal in proposals {
        // Skip empty patches
        if proposal.changed_files.is_empty() && proposal.unified_diff.trim().is_empty() {
            report.applied.push(proposal.task_name.clone());
            continue;
        }

        // Scope validation
        if let Some((allowed, forbidden)) = task_scopes.get(&proposal.task_name) {
            let scope_result = validate_scope(proposal, allowed, forbidden);
            if !matches!(scope_result, MergeResult::Applied) {
                report.scope_violations.push(scope_result);
                continue;
            }
        }

        // Check for conflicts with already-applied patches
        let conflicting: Vec<String> = proposal
            .changed_files
            .iter()
            .filter(|f| touched_files.contains(f.as_str()))
            .cloned()
            .collect();

        if !conflicting.is_empty() {
            report.apply_failures.push(MergeResult::ApplyFailed {
                task_name: proposal.task_name.clone(),
                error: format!(
                    "Conflicts with previously applied patches on files: {}",
                    conflicting.join(", ")
                ),
            });
            continue;
        }

        // Apply the patch
        match apply_patch_to_workspace(workspace_root, &proposal.unified_diff) {
            Ok(()) => {
                for file in &proposal.changed_files {
                    touched_files.insert(file.clone());
                }
                report.applied.push(proposal.task_name.clone());
            }
            Err(error) => {
                report.apply_failures.push(MergeResult::ApplyFailed {
                    task_name: proposal.task_name.clone(),
                    error,
                });
            }
        }
    }

    report
}
